/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <HE_IN_PIN.h>
#include <HE_IN_PIN_aliases.h>
#include <LCD.h>
#include <MOTOR_PWM.h>
#include <PWM_OUT_PIN.h>
#include <PWM_OUT_PIN_aliases.h>
#include <MOTOR_PWM_CLK.h>
#include <HE_ISR.h>
#include <HE_TIMER_CLK.h>
#include <HE_TIMER.h>
#include <COM_SYNC_OUT_PIN.h>
#include <COM_SYNC_OUT_PIN_aliases.h>
#include <VERT_SYNC_OUT_IN.h>
#include <VERT_SYNC_OUT_IN_aliases.h>
#include <CAM_READ_ISR.h>
#include <CAM_COUNTER.h>
#include <VSYNC_ISR.h>
#include <STEERING_PWM_OUT_PIN.h>
#include <STEERING_PWM_OUT_PIN_aliases.h>
#include <STEERING_PWM.h>
#include <STEERING_PWM_CLK.h>
#include <COM_VID_IN_PIN.h>
#include <COM_VID_IN_PIN_aliases.h>
#include <CAM_ADC.h>
#include <CAM_LINE_ISR.h>
#include <CAM_LINE_CLK.h>
#include <LCD_LCDPort.h>
#include <LCD_LCDPort_aliases.h>
#include <CAM_ADC_AMux.h>
#include <CAM_ADC_Ext_CP_Clk.h>
#include <CAM_ADC_IRQ.h>
#include <CAM_ADC_theACLK.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

